[package]
name = "pyth_example"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]

Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet", override = true }


[dependencies.Pyth]
local = "../../../pyth-crosschain/target_chains/sui/contracts"

[dependencies.Wormhole]
local = "../../../wormhole/sui/wormhole"

[dependencies.usdc]
local = "../../../stablecoin-sui/packages/usdc"


[addresses]
pyth_example = "0x0"


[dev-dependencies]


[dev-addresses]
